# Generated by Django 5.2.6 on 2025-10-21 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(help_text='OnlyID', max_length=64, unique=True, verbose_name='WechatOpenID')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='nickname')),
                ('avatar_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='avatarURL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last_login')),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联认证用户')),
            ],
            options={
                'verbose_name': 'WechatUser',
                'verbose_name_plural': 'WechatUsers',
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
