# Generated by Django 5.2.6 on 2025-11-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': True},
        ),
    ]
