# Generated by Django 5.2.6 on 2025-11-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitems_options_alter_orders_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False},
        ),
    ]
